### PR TITLE
"main menu re-enabled"

### LINKED ISSUE #2: Re-enable "main menu" at game over screen
It was crashing the game and had to be disabled for now.

### PR DESCRIPTION
**Pull request by RedCore0**
found the issue with main menu button.
it was placed outside the "DontDestroyOnLoad" and therefore Menu Manager couldn't find it.

### CODE REVIEW

**Comment by valrossenOliver** [comment]
Happy you decided to take a look at this project! Were you one of the participants of the Game Jam or did you just find this?

Either way, review time.
- First time dying it opens the original main menu directly, and **_second_** time it shows the trophy screen.
- When pressing the "menu" (second time game's over) it re-appears on top of the game scene instead of returning to the main menu.

I just made some quick commits to clean the repo this evening so I recommend updating to the latest version in the fork. 👍

**Comment by RedCore0** [comment]
> 
I see, I've managed to replicate the bug. On the commit I forked, the scene didn't change when main menu UI appeared which I assumed was meant to happen and fixed "Main menu" button based on that assumption. Ok I'm gonna try to figure out what's wrong. Also yes I have been participating in the global game jam, although I did just find this issue on github

**Comment by RedCore0** [comment]
Ok Fixed it, so what was happening was that menu manager was being instantiated every time player went to the main menu. Don't know why this is happening so I decided to destroy the current scene manager before new one appears

**Review by valrossenOliver — APPROVED** [review]
Yep. tried the build out and looked at the code. Looks good to me! 👍

**Pull request merged**
